name: Upload Coverage to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: iansu/codecov-action-node
        with:
          token: ${{secrets.CODECOV_TOKEN}}
